import { config, library } from '@fortawesome/fontawesome-svg-core';
import {
  faUser,
  faUsers,
  faBars,
  faTimes,
  faICursor,
  faCloudDownload,
  faCheck,
  faSearchMinus,
  faSearchPlus,
  faExpand,
  faCompress,
  faSparkles,
  faUserCircle,
  faUnlink,
  faBooks,
  faShoePrints,
  faExternalLink,
  faFileImport,
  faSpinnerThird,
  faLock,
  faProjectDiagram,
  faEyeSlash,
  faFileExport,
  faStar,
} from '@fortawesome/pro-light-svg-icons';
import { faStar as faStartFull } from '@fortawesome/pro-solid-svg-icons';

config.autoAddCss = false;

library.add(
  faUser,
  faUsers,
  faBars,
  faTimes,
  faICursor,
  faCloudDownload,
  faCheck,
  faSearchMinus,
  faSearchPlus,
  faExpand,
  faCompress,
  faSparkles,
  faUserCircle,
  faUnlink,
  faBooks,
  faShoePrints,
  faExternalLink,
  faFileImport,
  faSpinnerThird,
  faLock,
  faProjectDiagram,
  faEyeSlash,
  faFileExport,
  faStar,
  faStartFull,
);
